
#include <gtest/gtest.h>
#include "../sqrt.cpp"
#include <iostream>
#include <curl/curl.h>
#include <string>
#include <cstdlib>
#include <json/json.h>
#include "../includes/suffixtrie.h"
#include "../includes/logic.cpp"

using namespace std;

string testdata1 = "he assisted south african dissidents like the journalist donald woods whose story was told in the movie cry freedom$";
string testdata2 = "a proposal to make new york the third state to ban menthol cigarettes has created a furious and expensive lobbying war$";
string testdata3 = "the troubled lender is working on a lifeline but time is running out first republic is limping into the weekend days after reporting disastrous firstquarter results the bank is still working on a lifeline with some involved saying it is touch and go whether the federal government will assist in some way dealbook hears five countries whose farmers have been hurt by the policy including poland will get carveouts and compensation under an agreement reached friday brussels ukraines grains will continue to enter the european union tarifffree for another year despite protests from neighbors such as poland which have seen their own farmers hurt by the influx of cheaper foodstuffs the oil industry enjoyed record profits in after russia invaded ukraine but the prices of oil and natural gas have fallen sharply in recent months exxon mobil and chevron the two largest american oil companies reported modest earnings growth on friday as they were forced to manage their businesses in the face of sagging prices for oil and natural gas as the countrys oldest power station closed experts warn that the country needs a clearer strategy to manage its exit from coal power when it was first announced in that australias oldest power station liddell would close the news set off a political firestorm the metropolitan transportation authority said it would no longer provide service information on twitter because the reliability of the platform can no longer be guaranteed realtime train delays bus route changes and other service information that would be vital to millions of new york city commuters will no longer be shared on twitter because the reliability of the platform can no longer be guaranteed a metropolitan transportation authority official said on thursday long school closures have put public education and randi weingarten the leader of a major teachers union on the defensive during the early months of the covid pandemic randi weingarten and the teachers union she leads faced a vexing question when should schools the countries that use the euro recorded economic expansion of percent in the first quarter a slight improvement over the previous quarters flat output over a year after russias invasion of ukraine europes economy is showing signs of avoiding the worst expectations that it will fall into a recession the countries that use the euro currency expanded slightly in the first quarter despite high energy prices and a rise in the cost of most basic goods europes statistics agency reported friday a song generated by a i could have farreaching consequences for the future of the music industry this month an anonymous producer jolted the music industry by using artificial intelligence to impersonate the singers drake and the weeknd creating a fake track heart on my sleeve that quickly went viral richard sharp stepped down after an investigation concluded that he failed to disclose his involvement in arranging a loan for the former prime minister boris johnson the chairman of bbcs board richard sharp resigned on friday after an investigation concluded that he failed to disclose his involvement in arranging a nearly million loan for the former prime minister boris johnson once a symbol of affluence the stretch limo has largely fallen out of favor as the rise of uber and lyft the great recession and new regulations hastened a shift to chauffeured vans and s u v s over a few days in early march carmakers and limousine company operators gathered at the mgm grand in las vegas for an annual convention where they went to panels and parties and admired shiny new party buses vans and black sport utility vehicles$";


TEST(InsertAndSearchTest, SuffixFound)
{
    TrieNode testObj;
    TrieNode *testCurr = new TrieNode();
    ASSERT_EQ(1, suffixInsertionHelper(testObj, testdata1, testCurr));
    std::string searchString = "movie cry freedom";
    ASSERT_EQ(1, subStringSearchHelper(testObj, testdata1, testCurr, searchString));

}

TEST(InsertAndSearchTest, SuffixNotFound)
{
    TrieNode testObj;
    TrieNode *testCurr = new TrieNode();
    ASSERT_EQ(1, suffixInsertionHelper(testObj, testdata2, testCurr));
    std::string searchString = "fourth state";
    ASSERT_EQ(0, subStringSearchHelper(testObj, testdata1, testCurr, searchString));

}

TEST(InsertTest, WordInsert)
{
    TrieNode testObj;
    TrieNode *testCurr = new TrieNode();
    ASSERT_EQ(1, wordInsertionHelper(testObj, testdata1, testCurr));
}


int main(int argc, char **argv)
{
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}


